version: 2.1
orbs:
  slack: circleci/slack@4.10
jobs:
  test:
    docker:
      - image: archlinux
    environment:
      GTEST_COLOR: yes # Google Test の出力が白黒にならないようにする
    steps:
      - checkout
      - run:
          command: pacman -Syu --noconfirm make clang gtest
      - run:
          command: cd my; make clean all
      - run:
          command: cd my; make testall
      - slack/notify:
          event: fail
          template: basic_fail_1
workflows:
  test_and_notify:
    jobs:
      - test:
          context: slack
