version: 2.1
orbs:
  slack: circleci/slack@4.10
jobs:
  test:
    docker:
      - image: archlinux
      # - image: fedora
    steps:
      - checkout
      - run:
          command: pacman -Sy --noconfirm make clang gtest
          # command: dnf -y install make clang gtest
      - run:
          command: cd my; make testall
      - slack/notify:
          event: fail
          template: basic_fail_1
workflows:
  slack:
    jobs:
      - test:
          context: slack
