services:
  gtest:
    container_name: gtest
    image: skkzsh/gtest
    build: .
    environment:
      TZ: Asia/Tokyo
    volumes:
      - $PWD:/work
    working_dir: /work
    platform: linux/amd64 # archlinuxがamd64しかないため
